# Generated by Django 5.2.7 on 2025-10-30 06:53

from decimal import Decimal
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry',
            name='extra_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional work hours not covered by start/end time', max_digits=4),
        ),
        migrations.AddField(
            model_name='workentry',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=6),
        ),
    ]
